services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://namestekayo:Gyeky8Wu1W4e2FDi@zemon-database.w11mn.mongodb.net/?retryWrites=true&w=majority&appName=zemon-database
      - NODE_ENV=production
    depends_on:
      - mongodb
      - backend
    networks:
      - spherex-network
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb+srv://namestekayo:Gyeky8Wu1W4e2FDi@zemon-database.w11mn.mongodb.net/?retryWrites=true&w=majority&appName=zemon-database
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - spherex-network
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - spherex-network
    restart: always

networks:
  spherex-network:
    driver: bridge

volumes:
  mongodb_data: 